---
modules:
  # rather than one big rpm-ostree or dnf module, split things up into small, logical chunks
  # lots of modules avoids one multi-GB layer that changes whenever any dependency updates
  - type: rpm-ostree
    install:
      - atuin
      - bat
      - btop
      - direnv
      - fd-find
      - procs
      - ripgrep
  - type: rpm-ostree
    install:
      - autorestic
      - restic
      - rclone
  - type: rpm-ostree
    install:
      - git
      - git-extras
      - git-lfs
  - type: rpm-ostree
    install:
      - neovim
  - type: rpm-ostree
    install:
      - tailscale
  - type: rpm-ostree
    install:
      - tmux
      - which
      - zsh
  - type: rpm-ostree
    install:
      - udev
  - type: rpm-ostree
    install:
      - unzip
      - zip
  - type: rpm-ostree
    install:
      - urlview
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      allow-erasing: true
      packages:
        - starship
  - type: dnf
    repos:
      copr:
        - atim/gping
    install:
      allow-erasing: true
      packages:
        - gping
  - type: dnf
    repos:
      copr:
        - mecattaf/duoRPM
    install:
      allow-erasing: true
      packages:
        - eza
  - type: dnf
    repos:
      copr:
        - clarlok/tools
    install:
      allow-erasing: true
      packages:
        - zellij
  - type: dnf
    repos:
      copr:
        - brirec/interception-tools
    install:
      allow-erasing: true
      packages:
        - caps2esc
        - interception-tools
  - type: dnf
    repos:
      copr:
        - arun54321/ananicy-cpp
    install:
      allow-erasing: true
      packages:
        - ananicy-cpp
  - type: script
    snippets:
      - "git clone --depth=1 https://github.com/mattmc3/antidote.git /usr/share/zsh-antidote"
  - type: files
    files:
      - source: system
        destination: /
  - type: systemd
    system:
      enabled:
        - tailscaled
        - udevmon
