---
modules:
  - type: rpm-ostree
    install:
      - atuin
      - bat
      - btop
      - direnv
      - docker
      - fd-find
      - git
      - neovim
      - podman
      - polkit-kde
      - procs
      - ripgrep
      - tailscale
      - tmux
      - unzip
      - urlview
      - which
      - zip
      - zsh
  - type: dnf
    repos:
      copr:
        - atim/starship
        - atim/gping
        - mecattaf/duoRPM
        - clarlok/tools
    install:
      allow-erasing: true
      packages:
        - eza
        - gping
        - starship
        - zellij
  - type: systemd
    system:
      enabled:
        - tailscaled
  - type: script
    snippets:
      - "git clone --depth=1 https://github.com/mattmc3/antidote.git /usr/share/zsh-antidote"
