---
type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
install:
  - atuin
  - bat
  - btop
  # TODO: move out into chezmoi module https://blue-build.org/reference/modules/chezmoi/
  - chezmoi
  - direnv
  - docker
  - eza
  - fd
  - git
  - gping
  - neovim
  - podman
  - procs
  - ripgrep
  - starship
  - tailscale
  - tmux
  - unzip
  - urlview
  - which
  - zellij
  - zip
  - zsh
