---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: joshmock-hyprland
description: joshmock's Hyprland OS image

base-image: ghcr.io/wayblueorg/hyprland-nvidia-open
image-version: latest

modules:
  - from-file: hyprland.yml
  - from-file: base.yml
  - from-file: laptop.yml
  - from-file: apps.yml
  - type: bling
    install:
      - 1password
